@BASE_URL = http://localhost:3001/api

### Login
POST {{BASE_URL}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "abcer35",
  "password": "dfasdfdf"
}

### Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "abc456",
  "password": "password"
}
