@BASE_URL = http://localhost:3001/api
@AccessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl9uYW1lIjoiYWJjZGVmMiIsImlhdCI6MTc2NTcyODMwNywiZXhwIjoxNzY1ODE0NzA3fQ.rtg2eg-ipWhft6kIDn8bR592s5AlvZ98sDHcRvTDdvE

### Login
POST {{BASE_URL}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrEmail": "abcdef2",
  "password": "abcdef"
}

### Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "abcdef2",
  "email": "abcd2@gmail.com",
  "first_name": "ABC",
  "last_name": "DEF",
  "password": "abcdef"
}


### User
GET {{BASE_URL}}/user
Content-Type: application/json
Accept: application/json
Authorization: {{AccessToken}}


