@BASE_URL =http://localhost:3001/api
@AccesToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl9uYW1lIjoiYWJjZGVmMiIsImlhdCI6MTc2NjUwMDUzMCwiZXhwIjoxNzY2NTg2OTMwfQ.wvR5bwvzcYcRvbZiuRXeDJeO5wD8WAycwQLpvtVQE3g

### get category  list
GET {{BASE_URL}}/master/category?offset=10&limit=10
Content-Type: application/json
Accept: application/json

### create category 
POST {{BASE_URL}}/master/category
Content-Type: application/json
Accept: application/json
Authorization: {{AccesToken}}

{
    "category_name": "computer",
    "category_descriptions": "All kinds of compute items"
}


### create collection 
POST {{BASE_URL}}/master/collection
Content-Type: application/json
Accept: application/json
Authorization: {{AccesToken}}

{
    "collection_name": "summer",
    "collection_descriptions": "All kinds of summmer items"
}

### get collection list
GET {{BASE_URL}}/master/collection
Content-Type: application/json
Accept: application/json



### get category list
GET {{BASE_URL}}/master/category
Content-Type: application/json
Accept: application/json


### create category 
POST {{BASE_URL}}/master/category
Content-Type: application/json
Accept: application/json
Authorization: {{AccesToken}}

{
  "category_name": "Beauty",
  "category_descriptions": "Category for beauty products"
}