@BASE_URL = http://localhost:3001/api
@AccessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcl9uYW1lIjoiYWJjZGVmMiIsImlhdCI6MTc2NjMyMjkwOSwiZXhwIjoxNzY2NDA5MzA5fQ.TIon7t7_03EM1nZieo_O8h25WYdmtKgFe26l_l-N0EI


### get category list
GET {{BASE_URL}}/master/category
Content-Type: application/json
Accept: application/json


### create category 
POST {{BASE_URL}}/master/category
Content-Type: application/json
Accept: application/json
Authorization: {{AccessToken}}

{
  "category_name": "Beauty",
  "category_descriptions": "Category for beauty products"
}